### ISSUE TITLE
請問能否研究下兼容這個樣式

### ISSUE THREAD

**Issue by YheonYeung** [KazeLiu/GetDmhyDownloadUrl#1]
感謝這個提取磁連的腳本，剛剛發現之前一直用的那個批量腳本失效了。
一直在用一個樣式，版面文字都比較大容易看，希望把這個腳本也兼容上。
樣式需要先安裝Chrome擴充 xStyle或Stylish。感謝。
https://userstyles.org/styles/133936/acg-bt

![image](https://user-images.githubusercontent.com/63342274/183257449-f1569e34-3da0-4de2-9226-4c8a33ef02d7.png)
![image](https://user-images.githubusercontent.com/63342274/183257477-ff16ec56-af1f-428d-9d14-9dafd6ff7c5a.png)
![image](https://user-images.githubusercontent.com/63342274/183257484-18cccf03-7953-48ad-944b-3d79537a1c30.png)

**Comment by KazeLiu** [comment]
请问一下这个样式是怎么出来的？是装了什么插件吗？我无法复现

**Comment by KazeLiu** [comment]
好的 我看见了 今天有时间就更新

**Comment by KazeLiu** [comment]
已更新，感谢反馈

**Comment by YheonYeung** [comment]
感謝。現在這樣容易看得清。
